### ISSUE TITLE
Translations missing

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud-libraries/nextcloud-vue-collections#120]
Translations in core are not parsed since they are just a comment: https://github.com/nextcloud/server/blob/b479af83f06ae4d5330827a78d278d9266f514c0/core/src/OCP/collaboration.js#L37-L45 

@skjnldsv We don't have any translation mechanism for the vue-components as well at the moment, right?

**Comment by juliushaertl** [comment]
@MorrisJobke Would adding the transifex bot to this repo also just push translations to the core translations if they are in like this t('core', 'Add to a project') or would we need to setup some actual translation handling in the components repo.

**Comment by skjnldsv** [comment]
@juliushaertl related: https://github.com/nextcloud/nextcloud-vue/issues/97

**Comment by MorrisJobke** [comment]
> @MorrisJobke Would adding the transifex bot to this repo also just push translations to the core translations if they are in like this t('core', 'Add to a project') or would we need to setup some actual translation handling in the components repo.

That is the big problem. The bot can only push one set of strings and overwrites with this all of the ones from before. So it would need to be extracted inside the core or it need a separate repo, that then is shipped with core, which makes it also harder. Additionally it also needs to extract the correct version of the used nextcloud-vue package to not miss old translations that are shipped in apps or in old server versions. Any ideas for this?

**Comment by MorrisJobke** [comment]
Best would be if we can put the translations right in here and then continuously update them in here. Then also the apps ship those translations, but we don't need to keep them for eternity. Drawback: it needs to ship a lot of translations and that may be a big disadvantage, because it's also another mechanism (from the load apps translations which we already have in the server).

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/nextcloud-l10n/pull/88 will help, I think :)

**Comment by susnux** [comment]
Fixed with migrating to `@nextcloud/vue`
