### ISSUE TITLE
Migrate to Vue 3

### ISSUE THREAD

**Issue by ShGKme** [nextcloud-libraries/nextcloud-vue-collections#1201]

**Comment by ShGKme** [comment]
We may start with migrating https://github.com/nextcloud-libraries/nextcloud-vue-collections/blob/master/src/collectionstore.js to Vue 2.7 reactivity function first in `master`.

And then create a new branch with `@nextcloud/vue@9`

**Comment by DorraJaouad** [comment]
There is nothing to change in Template Directives as I checked.

**Comment by ShGKme** [comment]
But it still should have different dependencies — Vue 3 and `@nextcloud/vue@9`, so we need a new branch anyway...
